name: Build BLHX.Server
on: [push, pull_request]  # 触发条件：代码推送或PR时运行

jobs:
  build:
    runs-on: ubuntu-latest  # 使用 Ubuntu 环境
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # 检出代码

      - name: Set up .NET (示例：假设项目是C#)
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'  # 根据项目要求调整版本

      - name: Build project
        run: dotnet build BLHX.Server.sln  # 替换为实际构建命令

      - name: Run tests (可选)
        run: dotnet test